In [ ]:
"""Name-Jigyasa Rana
University roll no.-2028439
Section-P
"""

In [7]:
import warnings
warnings.filterwarnings('ignore')

In [8]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [9]:
data = pd.read_csv(r"C:\Users\ASUS\Downloads\market_basket_dataset.csv")
data.head(5)

   Item1   Item2   Item3 Item4
0   Milk   Bread  Butter  Eggs
1  Bread  Butter     Jam   NaN
2   Milk   Bread    Eggs   NaN
3   Milk   Bread  Butter   Jam
4  Bread    Eggs     Tea   NaN

In [11]:
transactions = df.values.tolist()

In [12]:
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

In [13]:
basket = pd.DataFrame(te_array, columns=te.columns_)
basket.head()

   False  True
0  False   True
1   True   True
2   True   True
3   True   True
4   True   True

In [14]:
frequent_itemsets = apriori(basket, min_support=0.3, use_colnames=True)

In [15]:
frequent_itemsets

   support                  itemsets
0      0.8        frozenset({False})
1      1.0         frozenset({True})
2      0.8  frozenset({False, True})

In [16]:
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

In [17]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,frozenset({False}),frozenset({True}),0.8,1.0,0.8,1.0,1.0,1.0,0.0,inf,0.0,0.8,0.0,0.9
1,frozenset({True}),frozenset({False}),1.0,0.8,0.8,0.8,1.0,1.0,0.0,1.0,0.0,0.8,0.0,0.9

In [18]:
frequent_itemsets[['support','itemsets']]

   support                  itemsets
0      0.8        frozenset({False})
1      1.0         frozenset({True})
2      0.8  frozenset({False, True})

In [19]:
rules[['antecedents','consequents','support','confidence']]

          antecedents         consequents  support  confidence
0  frozenset({False})   frozenset({True})      0.8         1.0
1   frozenset({True})  frozenset({False})      0.8         0.8